AllCops:
  TargetRubyVersion: 2.5

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: nested
  Exclude:
    - "test/**/*"

Style/ModuleFunction:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingUnderscoreVariable:
  Enabled: false

Metrics/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/AlignParameters:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false
